project:
  type: website

website:
  title: "Hands-on Practice on Sharing Outputs with the Audience"
  navbar:
    background: "#6a81a5"
    left:
      - href: https://lqpn2m-kathleen0juarez.shinyapps.io/channel-engagement-explorer/
        text: Shiny App
      - href: index.qmd
        text: Home
      #- href: shiny-app.qmd
      #  text: Shiny App Essay
      - href: CEP_dashboard.qmd
        text: Quarto Dashboard
      #- href: Shiny-live.qmd
      #  text: Shiny Live
        
        
        
    
format:
  html:
    theme:
      - minty
    toc: false

editor: visual

