project:
  type: website

website:
  title: "K.Juarez W11-Hands-on Practice"
  navbar:
    background: "#6a81a5"
    left:
      - href: index.qmd
        text: Home
      - href: shiny-app.qmd
        text: Shiny App 
      - href: CEP_dashboard.qmd
        text: Quarto Dashboard
   
        
        
        
    
format:
  html:
    theme:
      - minty
    toc: false

editor: visual

